extends:
  - "react-app"
  - "prettier"
plugins:
  - "prettier"
  - "react"
settings:
  react:
    version: "16.4.1"
globals:
  Feature: true
  Scenario: true
  Data: true
rules:
  no-debugger: ["error"]
  no-restricted-globals: [2, "localStorage", "sessionStorage"]
  prettier/prettier: ["error"]
  no-console: ["warn"]
  no-unneeded-ternary: ["warn", {
    "defaultAssignment": false
  }]
  no-confusing-arrow: ["off"]
  jsx-a11y/no-static-element-interactions: ["warn"]
  react/prop-types: ["off"]
  react/require-default-props: ["warn"]
  react/no-unused-prop-types: ["warn"]
  no-unused-vars: "off"
  react/require-optimization: ["warn"]
  react/no-redundant-should-component-update: ["warn"]
  react/jsx-key: ["warn"]
  react/prefer-stateless-function: ["warn"]
  react/jsx-handler-names: ["warn", {
    "eventHandlerPrefix": "handle",
    "eventHandlerPropPrefix": "on"
  }]
  react/no-direct-mutation-state: ["error"]
  react/jsx-no-literals: ["error", {"noStrings": true}]
  react/sort-comp:
    - "off"
  react/no-string-refs: "error"
overrides:
  - files: ["*.js"]
    rules:
      react/jsx-no-literals: ["off"]
  - files: ["*.stories.*"]
    rules:
      react/jsx-no-literals: ["off"]
  - files: ["*.js"]
    rules:
      no-console: ["off"]
  - files:
      - packages/backend/src/**/*.js
      - config/**/*.js
      - script/**/*.js
    excludedFiles: "config/polyfills.js"
    parserOptions:
      sourceType: "script"
    rules:
      strict: ["error", "global"]
  - files: ["*.stories.js"]
    rules:
      react/jsx-no-literals: ["off"]
